name: UI tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests'
        required: true
        default: chromium
        type: choice
        options:
          - chromium
          - firefox
          - webkit

      parallelTests:
        description: 'Run tests in parallel'
        required: true
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Install system dependencies for browsers
        run: sudo ./mvnw exec:java -e -Dexec.classpathScope=test -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"

      - name: Install Playwright browser
        run: ./mvnw exec:java -e -Dexec.classpathScope=test -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install ${{ inputs.browser || 'chromium' }}"

      - name: Run tests
        run: ./mvnw clean verify -DparallelTests=${{ inputs.parallelTests || 'true' }} -Dbrowser=${{ inputs.browser || 'chromium' }} -Dtest="com.example.playwrightdemo.ui.tests.*Tests"